version: "3.8"
services:
  node-app:
    build: .
    ports:
      - "8000:8000"
      - "3000:8000"
      - "4000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
    links:
      - redis
    expose:
      - $PORT
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
